version: "3.8"

services:
  app:
    container_name: fashion-store-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    image: fashion-store-app:latest
    networks:
      - nginx_proxy
    restart: unless-stopped
    env_file:
      - .env.prod

networks:
  nginx_proxy:
    external: true
