version: '3.8'
services:
  app:
    container_name: fashion-store-api
    build:
      context: .
      dockerfile: Dockerfile
    image: fashion-store-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - default
      - nginx_proxy
    restart: unless-stopped

networks:
  default:
    driver: bridge
  nginx_proxy:
    external: true