version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: fashion-store-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped